// This has been adapted from the Vulkan tutorial
#include <sstream>
#include <vector>
#include <cstdint>
#include <cmath>

#include "modules/Starter.hpp"

// Vertex definition
struct Vertex {
    glm::vec3 pos;		// now it defines the minimal parameters to support smooth shading in 3D
    glm::vec3 norm;
    glm::vec2 UV;
};

// The uniform buffer objects used in this example

// A local uniform buffer object with matrices and material parameters
struct UniformBufferObject {
    alignas(16) glm::mat4 vpMat;
    alignas(16) glm::vec4 specular;
    alignas(16) glm::vec3 ambient;
};

// A local uniform buffer for the instances
struct InstanceUniformBufferObject {
    alignas(16) glm::mat4 mMat[674];
};

// A local uniform buffer for creating the map
struct MapMakeUniformBufferObject {
    alignas(16) glm::mat4 Transform;
    alignas(16) glm::vec4 Color;
};

// A global uniform buffer object with lights and eye position
struct GlobalUniformBufferObject {
    alignas(16) glm::vec3 lightDir;
    alignas(16) glm::vec3 lightColor;
    alignas(16) glm::vec3 eyePos;
    alignas(16) glm::vec3 ambientLight;
};


// Push constants: this is the data structure for the push constants
struct PushConstants {
    glm::mat4 mMat;
    glm::mat4 uvMat;
};

// The following classes were generated by ChatGPT. This is a way to show a good use
// of IA based tools: the creation of the maze, is not  relevant with the course.
// It is then OK to leave this part to ChatGPT.

// This is the class containing the maze, and the procedure to create both the transform matrices
// for the walls, and the lines for the map.
class Labirynth
{
public:
    static constexpr int rows = 25;
    static constexpr int cols = 25;
    static constexpr float cellSize = 4.0f;

    struct LineMesh
    {
        std::vector<glm::vec3> vertices;
        std::vector<unsigned int> indices;
    };

    static std::vector<glm::mat4> generateWallTransforms()
    {
        std::vector<glm::mat4> transforms;

        constexpr float halfCell = cellSize * 0.5f;

        // Horizontal walls
        for (int r = 0; r < rows + 1; ++r)
        {
            for (int c = 0; c < cols; ++c)
            {
                if (horizontalWalls[r][c] == 1)
                {
                    float x = (c - cols * 0.5f + 0.5f) * cellSize;
                    float y = (rows * 0.5f - r) * cellSize;

                    glm::mat4 matrix(1.0f);
                    matrix = glm::scale(glm::mat4(1), glm::vec3(halfCell, halfCell, halfCell)) * matrix;
                    matrix = glm::translate(glm::mat4(1), glm::vec3(x, 1.0f, y)) * matrix;

                    transforms.push_back(matrix);
                }
            }
        }

        // Vertical walls
        for (int r = 0; r < rows; ++r)
        {
            for (int c = 0; c < cols + 1; ++c)
            {
                if (verticalWalls[r][c] == 1)
                {
                    float x = (c - cols * 0.5f) * cellSize;
                    float y = (rows * 0.5f - r - 0.5f) * cellSize;

                    glm::mat4 matrix(1.0f);
                    matrix = glm::scale(glm::mat4(1), glm::vec3(halfCell, halfCell, halfCell)) * matrix;
                    matrix = glm::rotate(glm::mat4(1), glm::radians(90.0f), glm::vec3(0, 1, 0)) * matrix;
                    matrix = glm::translate(glm::mat4(1), glm::vec3(x, 1.0f, y)) * matrix;

                    transforms.push_back(matrix);
                }
            }
        }

        return transforms;
    }

    static LineMesh generateLineMesh()
    {
        LineMesh mesh;

        auto addLine = [&](const glm::vec3& a, const glm::vec3& b)
        {
            unsigned int baseIndex = static_cast<unsigned int>(mesh.vertices.size());

            mesh.vertices.push_back(a);
            mesh.vertices.push_back(b);

            mesh.indices.push_back(baseIndex);
            mesh.indices.push_back(baseIndex + 1);
        };

        // Horizontal wall lines
        for (int r = 0; r < rows + 1; ++r)
        {
            for (int c = 0; c < cols; ++c)
            {
                if (horizontalWalls[r][c] == 1)
                {
                    float x0 = (c - cols * 0.5f) * cellSize;
                    float x1 = (c - cols * 0.5f + 1.0f) * cellSize;
                    float y  = (rows * 0.5f - r) * cellSize;

                    addLine(
                        glm::vec3(x0, y, 0.0f),
                        glm::vec3(x1, y, 0.0f)
                    );
                }
            }
        }

        // Vertical wall lines
        for (int r = 0; r < rows; ++r)
        {
            for (int c = 0; c < cols + 1; ++c)
            {
                if (verticalWalls[r][c] == 1)
                {
                    float x  = (c - cols * 0.5f) * cellSize;
                    float y0 = (rows * 0.5f - r) * cellSize;
                    float y1 = (rows * 0.5f - r - 1.0f) * cellSize;

                    addLine(
                        glm::vec3(x, y0, 0.0f),
                        glm::vec3(x, y1, 0.0f)
                    );
                }
            }
        }

        return mesh;
    }

public:
    inline static constexpr int horizontalWalls[rows + 1][cols] = {
        {1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1},
        {0,0,1,0,1,0,0,0,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,1,1},
        {1,1,0,0,0,1,0,1,1,0,1,0,1,0,0,0,1,0,0,0,1,1,1,0,0},
        {0,0,1,1,0,0,1,1,0,0,0,0,1,1,1,0,0,1,0,1,1,1,1,1,0},
        {0,1,0,1,1,0,0,0,1,1,1,1,0,1,0,0,1,1,0,0,0,0,0,1,0},
        {0,0,1,0,1,1,1,1,0,0,1,1,0,0,0,1,1,0,1,0,0,0,1,0,1},
        {0,1,1,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,1,0,1,0,1,0},
        {1,0,0,1,1,1,1,1,0,0,0,1,0,1,0,0,1,1,0,1,1,0,1,0,0},
        {0,1,1,0,1,1,1,0,0,0,1,0,1,1,1,1,0,0,0,0,1,1,0,1,0},
        {0,1,1,1,0,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,0,0,0,1},
        {0,1,0,1,1,0,0,1,0,1,1,0,1,0,1,0,1,1,1,1,0,0,0,1,0},
        {0,0,1,0,0,0,1,0,1,1,0,0,1,1,1,1,0,0,0,0,0,0,0,0,1},
        {0,1,0,1,1,1,0,1,0,0,1,0,0,1,0,0,1,1,0,1,1,0,0,1,0},
        {0,0,1,0,1,0,1,1,0,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0},
        {0,1,1,1,1,0,0,0,1,1,0,1,0,0,0,0,1,1,1,1,1,1,0,1,0},
        {1,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,1,1,0,0,1,1,1,1},
        {0,1,0,0,1,1,1,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0},
        {0,0,1,0,0,1,1,1,1,0,1,0,1,0,0,1,1,1,1,0,1,0,1,1,0},
        {0,1,0,1,1,1,1,0,0,0,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1},
        {0,0,1,0,1,0,0,1,0,0,1,1,1,0,1,0,1,1,1,1,1,0,0,1,0},
        {0,0,0,0,1,0,1,0,1,0,0,1,0,1,1,1,0,0,1,1,0,0,1,1,0},
        {0,0,0,0,0,1,0,1,0,1,0,0,1,1,0,0,1,1,0,1,0,1,0,0,0},
        {0,1,1,0,0,0,1,0,1,0,1,1,1,0,1,0,0,0,1,0,1,0,1,1,1},
        {0,0,0,1,0,1,0,0,0,0,0,1,1,1,0,1,1,0,0,0,0,1,0,1,0},
        {0,0,0,0,1,0,1,1,0,0,1,0,0,1,1,0,0,1,0,0,1,0,1,0,0},
        {1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1}
    };

    inline static constexpr int verticalWalls[rows][cols + 1] = {
        {1,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,1,0,0,1},
        {1,0,1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,1,1,1,1,0,0,1,0,1},
        {1,0,0,1,1,1,1,0,0,1,1,0,1,0,0,1,1,0,1,1,0,0,0,0,1,1},
        {1,1,1,0,0,1,0,1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1},
        {1,0,1,0,0,0,1,1,0,1,0,0,0,1,0,1,0,0,1,0,1,1,1,0,1,1},
        {1,1,0,0,1,0,1,0,1,1,1,0,1,1,1,1,0,1,1,0,1,1,0,1,0,1},
        {1,1,0,0,0,1,0,1,0,1,1,1,0,1,0,1,1,0,1,0,0,1,1,0,1,1},
        {1,0,1,1,0,0,0,0,1,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1},
        {1,0,0,0,1,0,0,0,1,1,0,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1},
        {1,0,1,0,0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,1,1,0,1},
        {1,1,0,1,0,1,0,1,1,0,0,1,1,0,0,0,1,0,1,0,1,1,1,1,0,1},
        {1,1,0,1,1,0,0,1,0,1,0,1,1,0,0,1,0,1,1,1,0,1,1,1,0,1},
        {1,1,0,1,0,0,1,0,0,1,1,0,1,0,1,1,0,0,1,1,0,1,1,0,1,1},
        {1,1,0,0,0,1,1,0,1,1,0,1,0,1,1,1,0,0,1,0,1,0,1,1,1,1},
        {1,0,1,1,0,1,1,1,0,0,1,0,1,0,1,1,1,0,0,0,1,0,0,0,0,1},
        {1,1,0,1,1,0,1,0,0,1,0,0,1,1,1,1,1,1,0,1,1,1,0,1,0,1},
        {1,1,0,1,1,0,0,0,0,1,0,0,1,0,1,1,0,0,0,1,0,1,1,0,0,1},
        {1,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,0,0,0,1,0,0,1,0,0,1},
        {1,1,0,1,0,0,0,1,0,1,1,0,0,0,1,1,0,0,0,1,0,0,1,1,0,1},
        {1,1,1,1,0,1,1,0,1,1,1,0,0,1,0,0,1,0,0,0,0,1,1,0,0,1},
        {1,1,1,1,1,0,1,0,1,0,1,1,0,0,0,1,0,1,0,1,0,0,1,0,1,1},
        {1,0,1,0,1,1,0,1,0,1,0,1,0,0,1,1,1,0,1,0,1,1,0,1,0,1},
        {1,1,0,1,1,1,0,1,1,1,1,0,0,1,0,1,0,1,1,1,1,0,1,0,0,1},
        {1,1,1,1,0,1,1,0,1,1,1,0,1,0,0,1,0,1,0,1,1,0,1,1,0,1},
        {1,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,1}
    };
};


// procedural textures for the walls and for the floor.
class ProceduralTextures
{
public:

    struct TextureData
    {
        int width;
        int height;
        std::vector<uint8_t> pixels; // RGBA8
    };

    static TextureData generateBrickWallTexture(
        int width = 512,
        int height = 512)
    {
        TextureData texture;
        texture.width = width;
        texture.height = height;
        texture.pixels.resize(width * height * 4);

        const int brickWidth  = 96;
        const int brickHeight = 48;
        const int mortarSize  = 4;

        for (int y = 0; y < height; ++y)
        {
            int rowIndex = y / brickHeight;

            // Offset every other row
            int rowOffset = (rowIndex % 2) * (brickWidth / 2);

            for (int x = 0; x < width; ++x)
            {
                int localX = (x + rowOffset) % brickWidth;
                int localY = y % brickHeight;

                bool isMortar =
                    localX < mortarSize ||
                    localY < mortarSize;

                if (isMortar)
                {
                    // Mortar color
                    setPixel(
                        texture,
                        x,
                        y,
                        190,
                        185,
                        175
                    );
                }
                else
                {
                    // Simple procedural variation
                    float noise =
                        0.85f +
                        0.15f *
                        std::sin(x * 0.11f) *
                        std::sin(y * 0.07f);

                    uint8_t r =
                        static_cast<uint8_t>(150 * noise);

                    uint8_t g =
                        static_cast<uint8_t>(55 * noise);

                    uint8_t b =
                        static_cast<uint8_t>(38 * noise);

                    setPixel(texture, x, y, r, g, b);
                }
            }
        }

        return texture;
    }

    static TextureData generateTileGridTexture(
        int width = 512,
        int height = 512)
    {
        TextureData texture;
        texture.width = width;
        texture.height = height;
        texture.pixels.resize(width * height * 4);

        const int tileSize  = 64;
        const int groutSize = 3;

        for (int y = 0; y < height; ++y)
        {
            for (int x = 0; x < width; ++x)
            {
                int localX = x % tileSize;
                int localY = y % tileSize;

                bool isGrout =
                    localX < groutSize ||
                    localY < groutSize;

                if (isGrout)
                {
                    // Grout color
                    setPixel(
                        texture,
                        x,
                        y,
                        80,
                        80,
                        85
                    );
                }
                else
                {
                    // Slight radial shading
                    float centerX = tileSize * 0.5f;
                    float centerY = tileSize * 0.5f;

                    float dx =
                        (localX - centerX) / centerX;

                    float dy =
                        (localY - centerY) / centerY;

                    float shade =
                        1.0f -
                        0.08f * (dx * dx + dy * dy);

                    uint8_t value =
                        static_cast<uint8_t>(210 * shade);

                    setPixel(
                        texture,
                        x,
                        y,
                        value,
                        value,
                        value + 8
                    );
                }
            }
        }

        return texture;
    }

private:

    static void setPixel(
        TextureData& texture,
        int x,
        int y,
        uint8_t r,
        uint8_t g,
        uint8_t b,
        uint8_t a = 255)
    {
        int index =
            4 * (y * texture.width + x);

        texture.pixels[index + 0] = r;
        texture.pixels[index + 1] = g;
        texture.pixels[index + 2] = b;
        texture.pixels[index + 3] = a;
    }
};

// utility function to find the closest point on a line segment, used for collision resolution
static glm::vec2 closestPointOnSegment(glm::vec2 p, glm::vec2 a, glm::vec2 b) {
    glm::vec2 ab = b - a;
    float t = glm::dot(p - a, ab) / glm::dot(ab, ab);
    t = glm::clamp(t, 0.0f, 1.0f);
    return a + t * ab;
}

// collision resolution function, that takes a position and a radius, and returns a new position that is not colliding with the walls
static glm::vec3 resolveCollisions(glm::vec3 pos, float radius) {
    constexpr float halfCell = Labirynth::cellSize * 0.5f;
    glm::vec2 p(pos.x, pos.z);

    for (int r = 0; r <= Labirynth::rows; r++) {
        for (int c = 0; c < Labirynth::cols; c++) {
            if (Labirynth::horizontalWalls[r][c] == 1) {
                float wx = (c - Labirynth::cols * 0.5f + 0.5f) * Labirynth::cellSize;
                float wz = (Labirynth::rows * 0.5f - r) * Labirynth::cellSize;
                glm::vec2 q = closestPointOnSegment(p, {wx - halfCell, wz}, {wx + halfCell, wz});
                glm::vec2 d = p - q;
                float dist = glm::length(d);
                if (dist > 0.0001f && dist < radius)
                    p = q + glm::normalize(d) * radius;
            }
        }
    }

    for (int r = 0; r < Labirynth::rows; r++) {
        for (int c = 0; c <= Labirynth::cols; c++) {
            if (Labirynth::verticalWalls[r][c] == 1) {
                float wx = (c - Labirynth::cols * 0.5f) * Labirynth::cellSize;
                float wz = (Labirynth::rows * 0.5f - r - 0.5f) * Labirynth::cellSize;
                glm::vec2 q = closestPointOnSegment(p, {wx, wz - halfCell}, {wx, wz + halfCell});
                glm::vec2 d = p - q;
                float dist = glm::length(d);
                if (dist > 0.0001f && dist < radius)
                    p = q + glm::normalize(d) * radius;
            }
        }
    }

    return {p.x, pos.y, p.y};
}

// This is were the part generated by ChatGPT ends. From this point on, when we really
// use the topics of the course, everything has been done by hand.
// Moreover, the two classes were generate with a deep supervision, where i understood
// everything ChatGPT did, because it was what i requested. Therefore, in an oral exam,
// i would be able to perfectly explain the concepts behind the procedure, and i would
// know precisely what every line of the previous code does.

// MAIN ! 
class Game : public BaseProject {
    protected:
    // Vertex formants, Pipelines and Render passes are always needed
    VertexDescriptor VD, VDmap;
    RenderPass RP;
    RenderPass RPmap;	// Render pass for the map

    Pipeline Pw;	// pipelines for the walls
    Pipeline Pf;	// pipelines for the floor
    Pipeline PwMap;	// pipelines for the walls when creating the map
    Pipeline PsMap;	// pipeline to show the map

    // Descriptor Layouts
    DescriptorSetLayout DSLlocalWalls, DSLlocalFloor, DSLsMap, DSLglobal, DSLmMap;

    // Descriptor sets
    DescriptorSet DSglobal;
    DescriptorSet DSlocalWalls, DSlocalFloor, DSlocalShowMap, DSlocalMakeMap;


    // Models
    Model M1, M2;

    // Textures
    Texture TWalls, TFloor;

    // to properly support the resizing of the windows, we need to store in a variable the aspect ratio
    float Ar;

    // to support camera motion, we also need to remember the position and
    // direction of the camera
    glm::vec3 CamPos = {0.0f, 1.0f, 4.0f};
    float Yaw = 0.0f;
    float Pitch = 0.0f;

    // the positions of the instances
    InstanceUniformBufferObject iubo;

    // for minimap
    int32_t Wframe = 16;
    float MapH = 128;
    float MapW = 128;

    // Here you set the main application parameters
    void setWindowParameters() {
        // initial window size and title
        windowWidth = 800;
        windowHeight = 600;
        windowTitle = "Haunted Castle Explorer";
        windowResizable = GLFW_TRUE;	// makes the window resizable

        // sets the aspect ratio
        Ar = (float)windowWidth / (float)windowHeight;
    }

    // What to do when the window changes size
    void onWindowResize(int w, int h) {
        // Update Render Pass (this must always be done for all render pass the depends on the screen size)
        RP.width = w;
        RP.height = h;

        // updates the aspect ratio
        Ar = (float)w / (float)h;
        windowWidth = w;
        windowHeight = h;
    }

    // Here you load and setup all your Vulkan Resources.
    void localInit() {
        // creates an empty vertex definition
        VD.init(this,
            {			// number of "bindings" that this vertex uses
                {0, sizeof(Vertex), VK_VERTEX_INPUT_RATE_VERTEX}	// binding number, size, and type
            }, {		// this must match the structure Vertex defined above
                  {0, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(Vertex, pos),
                         sizeof(glm::vec3), POSITION},
                  {0, 1, VK_FORMAT_R32G32B32_SFLOAT, offsetof(Vertex, norm),
                         sizeof(glm::vec3), NORMAL},
                  {0, 2, VK_FORMAT_R32G32_SFLOAT, offsetof(Vertex, UV),
                         sizeof(glm::vec2), UV}
            });

        VDmap.init(this,
            {
                {0, sizeof(glm::vec3), VK_VERTEX_INPUT_RATE_VERTEX}
            }, {
                  {0, 0, VK_FORMAT_R32G32B32_SFLOAT, 0,
                         sizeof(glm::vec3), POSITION},
            });

        // Descriptor Layouts [what will be passed to the shaders]
        DSLlocalWalls.init(this, {
                    {0, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_SHADER_STAGE_ALL_GRAPHICS, sizeof(UniformBufferObject), 1},
                    {1, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_SHADER_STAGE_FRAGMENT_BIT, 0,  1},  // albedo
                    {2, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_SHADER_STAGE_VERTEX_BIT,   sizeof(InstanceUniformBufferObject), 1}
                  });
        DSLlocalFloor.init(this, {
                    {0, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_SHADER_STAGE_ALL_GRAPHICS, sizeof(UniformBufferObject), 1},
                    {1, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_SHADER_STAGE_FRAGMENT_BIT, 0,  1}
                  });
        DSLmMap.init(this, {
                    {0, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_SHADER_STAGE_ALL_GRAPHICS, sizeof(MapMakeUniformBufferObject), 1}
                  });
        DSLsMap.init(this, {
                    {0, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_SHADER_STAGE_FRAGMENT_BIT, 0,  1}
                  });
        DSLglobal.init(this, {
                    {0, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_SHADER_STAGE_ALL_GRAPHICS, sizeof(GlobalUniformBufferObject), 1}
                  });


        // initializes the render passes (always needed)
        RP.init(this);
        // now the render pass for the map
        RPmap.init(this, MapW, MapH, 1,
                    RenderPass::getStandardAttchmentsProperties(AT_ONE_COLOR_AND_DEPTH, this),
                    RenderPass::getStandardDependencies(ATDEP_SIMPLE), true);

        // defines the pipeline, setting its vertex format and shaders
        Pw.init(this, &VD, "shaders/PosNormUVInstance.vert.spv", "shaders/LambertBlinnTexture.frag.spv", {&DSLglobal, &DSLlocalWalls});
        Pw.setCullMode(VK_CULL_MODE_NONE);

        PwMap.init(this, &VDmap, "shaders/Map.vert.spv", "shaders/Map.frag.spv", {&DSLmMap});
        PwMap.setTopology(VK_PRIMITIVE_TOPOLOGY_LINE_LIST);

        PsMap.init(this, &VD, "shaders/ShowMap.vert.spv", "shaders/ShowMap.frag.spv", {&DSLsMap});
        PsMap.setCullMode(VK_CULL_MODE_NONE);
/*		PsMap.setScissor({{{(int32_t)(windowWidth - MapW) - Wframe, (int32_t)(windowHeight - MapH) - Wframe},
                           {(uint32_t)MapW, (uint32_t)MapH}}});
*/
        // The pipeline for the floor, has also the push contstants
        Pf.init(this, &VD, "shaders/PosNormUVpc.vert.spv", "shaders/LambertBlinnTexture.frag.spv", {&DSLglobal, &DSLlocalFloor}, {{VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(PushConstants)}});

        // sets the size of the Descriptor Set Pool (we have 3: one global and two local)
        DPSZs.setsInPool = 5;
        // sets the number of uniforms : three, that is one per descriptor set
        DPSZs.uniformBlocksInPool = 5;
        // sets also the number of textures
        DPSZs.texturesInPool = 4;

        // create models
        M1.vertices = std::vector<unsigned char>(4 * sizeof(Vertex));
        Vertex *V_vertex = (Vertex *)(&(M1.vertices[0]));

        V_vertex[0] = {{-1.0, -1.0, 0.0}, {0.0, 0.0, -1.0}, {0.0, 0.0}};	// vertex 0
        V_vertex[1] = {{ 1.0, -1.0, 0.0}, {0.0, 0.0, -1.0}, {1.0, 0.0}};	// vertex 1
        V_vertex[2] = {{-1.0,  1.0, 0.0}, {0.0, 0.0, -1.0}, {0.0, 1.0}};	// vertex 2
        V_vertex[3] = {{ 1.0,  1.0, 0.0}, {0.0, 0.0, -1.0}, {1.0, 1.0}};	// vertex 3

        // Indices
        // In this case, indice would not be required, but we use them anyway to show how to do it
        M1.indices = {0, 2, 1,    1, 2, 3};

        // creates the mesh, using the define vertex format
        M1.initMesh(this, &VD);

        auto lineMesh = Labirynth::generateLineMesh();
        M2.vertices = std::vector<unsigned char>(lineMesh.vertices.size() * sizeof(glm::vec3));
        memcpy(&M2.vertices[0], &lineMesh.vertices[0], lineMesh.vertices.size() * sizeof(glm::vec3));
        M2.indices = lineMesh.indices;
        M2.initMesh(this, &VDmap);

        // Creates the textures
        auto wallTexture = ProceduralTextures::generateBrickWallTexture();
        TWalls.init(this, "assets/textures/granite-tile/granite-tile_albedo.png", VK_FORMAT_R8G8B8A8_SRGB, false);
        auto *tex_sampler = new TextureSampler();
        tex_sampler->init(this,
                             VK_FILTER_NEAREST,
                             VK_FILTER_NEAREST,
                             VK_SAMPLER_ADDRESS_MODE_REPEAT,
                             VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
                             VK_SAMPLER_MIPMAP_MODE_NEAREST,
                             VK_FALSE, 1, 0
        );
        TWalls.setSampler(tex_sampler);

        auto floorTexture = ProceduralTextures::generateTileGridTexture();
        TFloor.initPixels(this, floorTexture.width, floorTexture.height, 4, sizeof(uint8_t), {floorTexture.pixels.data()}, VK_FORMAT_R8G8B8A8_UNORM);

        submitCommandBuffer("main", 0, populateCommandBufferAccess, this, freeCommandBuffer);

        // creates the world matrices per instance
        auto wallMatrices = Labirynth::generateWallTransforms();
        memcpy(&iubo.mMat[0], &wallMatrices[0], sizeof(glm::mat4) * 674);
    }

    // Here you create your pipelines and Descriptor Sets!
    // this function is called whenever the geometry of the screen changes (for example when
    // the window is resized) to reconstruct the pipelines with the new resources
    void pipelinesAndDescriptorSetsInit() {
        // creates the render passes
        RP.create();
        RPmap.create();

        // update scissors and viewport
        PsMap.setScissor({{{(int32_t)(windowWidth - MapW) - Wframe, (int32_t)(windowHeight - MapH) - Wframe},
                           {(uint32_t)MapW, (uint32_t)MapH}}});

        PsMap.setViewport({{windowWidth - MapW - Wframe,
                            windowHeight - MapH - Wframe,
                            MapW, MapH, 0.0f, 1.0f}});

        // This creates the pipelines
        PwMap.create(&RPmap);
        PsMap.create(&RP);
        Pw.create(&RP);
        Pf.create(&RP);

        // Creates the descriptor sets
        DSglobal.init(this, &DSLglobal, {});
        DSlocalMakeMap.init(this, &DSLmMap, {});
        DSlocalWalls.init(this, &DSLlocalWalls, {TWalls.getViewAndSampler()});
        DSlocalFloor.init(this, &DSLlocalFloor, {TFloor.getViewAndSampler()});
        DSlocalShowMap.init(this, &DSLsMap, {RPmap.attachments[0].getViewAndSampler()});
    }

    // Here you destroy your pipelines and Descriptor Sets!
    // this function is called whenever the geometry of the screen changes (for example when
    // the window is resized) to free resources that are no longer valid
    void pipelinesAndDescriptorSetsCleanup() {
        PwMap.cleanup();
        PsMap.cleanup();
        Pw.cleanup();
        Pf.cleanup();

        RP.cleanup();
        RPmap.cleanup();

        DSglobal.cleanup();
        DSlocalWalls.cleanup();
        DSlocalFloor.cleanup();
        DSlocalShowMap.cleanup();
        DSlocalMakeMap.cleanup();
    }

    // Here you destroy all the Models, Texture and Desc. Set Layouts you created!
    // You also have to destroy the pipelines
    // this is called only once at the end of the application to free all the resources
    void localCleanup() {
        PwMap.destroy();
        PsMap.destroy();
        Pw.destroy();
        Pf.destroy();

        RP.destroy();
        RPmap.destroy();

        M1.cleanup();
        M2.cleanup();
        TWalls.cleanup();
        TFloor.cleanup();

        DSLlocalWalls.cleanup();
        DSLlocalFloor.cleanup();
        DSLsMap.cleanup();
        DSLmMap.cleanup();
        DSLglobal.cleanup();

    }

    // Here it is the creation of the command buffer:
    // You send to the GPU all the objects you want to draw,
    // with their buffers and textures
    static void populateCommandBufferAccess(VkCommandBuffer commandBuffer, int currentImage, void *Params) {
        // Simple trick to avoid having always 'T->'
        // in che code that populates the command buffer!
        Game *Mo = (Game *)Params;
        Mo->populateCommandBuffer(commandBuffer, currentImage);
    }

    void populateCommandBuffer(VkCommandBuffer commandBuffer, int currentImage) {
        // begin standard pass
        RPmap.begin(commandBuffer, 0);
        // selects a pipeline
        PwMap.bind(commandBuffer);
        //select the global descriptor set (valid for all objects)
        DSlocalMakeMap.bind(commandBuffer, PwMap, 0, 0);
        // selects the model
        M2.bind(commandBuffer);
        //select the local descriptor set for this object
//		DSlocalWalls.bind(commandBuffer, PwMap, 1, 0);		

        vkCmdDrawIndexed(commandBuffer, static_cast<uint32_t>(M2.indices.size()), 1, 0, 0, 0);

        RPmap.end(commandBuffer);




        // begin standard pass
        RP.begin(commandBuffer, currentImage);

        // selects a pipeline
        Pw.bind(commandBuffer);

        //select the global descriptor set (valid for all objects)
        DSglobal.bind(commandBuffer, Pw, 0, currentImage);

        // selects the model
        M1.bind(commandBuffer);

        //select the local descriptor set for this object
        DSlocalWalls.bind(commandBuffer, Pw, 1, currentImage);

        // draws something. This is a real Vulkan command, not wrapped by the system
        // note that now we use the "Indexed" version, since we have also the index buffer.
        // moreover, we can count the number of elements to write, from the size of the index array
        vkCmdDrawIndexed(commandBuffer, static_cast<uint32_t>(M1.indices.size()), 674, 0, 0, 0);






        // selects a pipeline
        Pf.bind(commandBuffer);
        //select the global descriptor set (valid for all objects)
        DSglobal.bind(commandBuffer, Pf, 0, currentImage);
        // selects the model
        M1.bind(commandBuffer);
        //select the local descriptor set for this object
        DSlocalFloor.bind(commandBuffer, Pf, 1, currentImage);

        // Draws the floor
        // creates and pases the push constants
        PushConstants constants;
        constants.mMat  = glm::translate(glm::mat4(1), glm::vec3(0,-1,0)) *
                          glm::rotate   (glm::mat4(1), glm::radians(90.0f), glm::vec3(1,0,0)) *
                          glm::scale    (glm::mat4(1), glm::vec3(60));
        constants.uvMat = glm::scale    (glm::mat4(1), glm::vec3(60));
        // ---- upload to the GPU via push constants
        vkCmdPushConstants(commandBuffer, Pf.pipelineLayout, VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(PushConstants), &constants);

        // draws the model.
        vkCmdDrawIndexed(commandBuffer, static_cast<uint32_t>(M1.indices.size()), 1, 0, 0, 0);



        // Draws the map. Note that in this case, one model fits all!
        PsMap.bind(commandBuffer);
        DSlocalShowMap.bind(commandBuffer, PsMap, 0, currentImage);
        vkCmdDrawIndexed(commandBuffer, static_cast<uint32_t>(M1.indices.size()), 1, 0, 0, 0);


        // Now draws the other model, using the same pipeline.
/*		M2.bind(commandBuffer);
        //select the local descriptor set for the other object
        DSlocal2.bind(commandBuffer, P, 1, currentImage);
        vkCmdDrawIndexed(commandBuffer, static_cast<uint32_t>(M2.indices.size()), 1, 0, 0, 0);
*/		
        // ends the current render pass
        RP.end(commandBuffer);
    }

    // if there are resources no longer needed, they are released here.
    // in this way, if you have for example mesh that are dynamically created, you can free them here
    // to avoid the memory to grow too much.
    static void freeCommandBuffer(void *Params) {
        // here there is no need of freeing anything, since all resources are for the entire application
    }

    // Here is where you update the uniforms.
    // Very likely this will be where you will be writing the logic of your application.
    void updateUniformBuffer(uint32_t currentImage) {
        // handle the ESC key to exit the app
        if(glfwGetKey(window, GLFW_KEY_ESCAPE)) {
            glfwSetWindowShouldClose(window, GL_TRUE);
        }

        // read the input states, to support interaction and animation
        float deltaT;
        glm::vec3 m = {0,0,0}, r = {0,0,0};
        bool fire = false;
        getSixAxis(deltaT, m, r, fire);

        // creates the global data structure for the uniforms
        // for the global descriptor set
        GlobalUniformBufferObject gubo;

        // fills with the relevant data
        gubo.lightDir = glm::vec3(0.5656854, 0.7071068, 0.4242641);
        gubo.lightColor = glm::vec3(1.0, 1.0, 1.0);
        // now the eye position corresponds to the position of the camera
        gubo.eyePos = CamPos;
        // now the ambient light color
        gubo.ambientLight = glm::vec3(0.05);

        // transfers the data to the GPU, by mapping it to its
        // descriptor set
        DSglobal.map(currentImage, &gubo, 0);


        // creates the local data structure for the uniforms
        // for the local descriptor sets
        UniformBufferObject ubo;

        // to support motion, we explicitly add the view and projection matrices.
        glm::mat4 View, Projection;
        // Camera FOV-y, Near Plane and Far Plane
        const float FOVy = glm::radians(90.0f);
        const float nearPlane = 0.1f;
        const float farPlane = 100.f;
        const float M_SPEED = 4.0;
        const float R_SPEED = 2.0;

        Projection = glm::perspective(FOVy, Ar, nearPlane, farPlane);
        Projection[1][1] *= -1;

        // update the camera position and direction with the inputs
        m.y /= 10.0;
        glm::vec3 newPos = CamPos + glm::vec3(glm::rotate(glm::mat4(1), Yaw, glm::vec3(0,1,0)) * glm::vec4(m * deltaT, 1.0)) * M_SPEED;
        CamPos = resolveCollisions(newPos, 0.5f);
        Pitch -= r.x * deltaT * R_SPEED;
        Yaw   -= r.y * deltaT * R_SPEED;

        View = glm::rotate   (glm::mat4(1), -Pitch, glm::vec3(1,0,0)) *
               glm::rotate   (glm::mat4(1), -Yaw,   glm::vec3(0,1,0)) *
               glm::translate(glm::mat4(1), -CamPos);


        // fills with the relevant data
        ubo.vpMat = Projection * View;
        ubo.specular = glm::vec4(1.0, 1.0, 1.0, 160.0);
        ubo.ambient = glm::vec3(1.0, 1.0, 1.0);
        // transfers the data to the GPU, by mapping it to its
        // descriptor set
        DSlocalWalls.map(currentImage, &ubo, 0);
        DSlocalFloor.map(currentImage, &ubo, 0);

        // sets the world matrices per instance
        DSlocalWalls.map(currentImage, &iubo, 2);

        MapMakeUniformBufferObject mmubo;
        glm::mat4 mTr = glm::mat4(1.0);
        mTr = glm::translate(glm::mat4(1.0), glm::vec3(-CamPos.x, -CamPos.z, 0.0f)) * mTr;
        mTr = glm::rotate(glm::mat4(1.0), Yaw, glm::vec3(0,0,1)) * mTr;
        mTr = glm::scale(glm::mat4(1.0), glm::vec3(0.05f)) * mTr;
        mmubo.Transform = mTr;
        mmubo.Color = glm::vec4(1,0,0,1);
        DSlocalMakeMap.map(currentImage, &mmubo, 0);
    }
};


// This is the main: probably you do not need to touch this!
int main() {
    Game app;

    try {
        app.run(false);
    } catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
